create table if not exists public.daily_checkins (
    id bigint generated by default as identity primary key,
    anonymous_id text not null,
    created_at timestamptz not null default now(),
    mood smallint not null check (mood between 1 and 7),
    stress smallint not null check (stress between 1 and 7),
    energy smallint not null check (energy between 1 and 7)
);

create table if not exists public.evaluation_sessions (
    id bigint generated by default as identity primary key,
    interaction_id uuid not null unique,
    anonymous_id text not null,
    created_at timestamptz not null default now(),
    mood_before smallint not null check (mood_before between 1 and 7),
    stress_before smallint not null check (stress_before between 1 and 7),
    energy_before smallint not null check (energy_before between 1 and 7),
    mood_after smallint not null check (mood_after between 1 and 7),
    stress_after smallint not null check (stress_after between 1 and 7),
    energy_after smallint not null check (energy_after between 1 and 7),
    felt_heard smallint not null check (felt_heard between 1 and 7),
    response_relevance smallint not null check (response_relevance between 1 and 7),
    would_use_again smallint not null check (would_use_again between 1 and 7)
);

create index if not exists daily_checkins_anonymous_id_index
on public.daily_checkins (anonymous_id);

create index if not exists evaluation_sessions_anonymous_id_index
on public.evaluation_sessions (anonymous_id);

alter table public.daily_checkins enable row level security;
alter table public.evaluation_sessions enable row level security;

-- No public policies are created. The Streamlit server uses a Supabase secret key
-- or a legacy service_role key. Never place either key in app.py, GitHub, or browser-side code.
